# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-07-05 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnlabeledComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text_raw', models.TextField()),
                ('text_preprocessed', models.TextField()),
                ('hashvalue', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserLabeledComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('label_user', models.CharField(max_length=255)),
                ('label_machine', models.CharField(max_length=255)),
            ],
        ),
    ]
