# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-07-05 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnlabeledCommentOld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text_raw', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='UnlabeledComment',
        ),
    ]
