# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-07-05 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_module', '0002_auto_20180705_1306'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UnlabeledCommentOld',
            new_name='UnlabeledComment',
        ),
    ]
