# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-08-14 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_module', '0002_remove_userlabeledcomment_label_machine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('text_raw', models.TextField()),
            ],
        ),
    ]
