# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-08-17 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_module', '0003_staging'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staging',
            name='title',
        ),
    ]
